#pragma once
#include <iostream>
#include <Windows.h>
#include <vector>
#include <TlHelp32.h>
#include <stdlib.h>
#include <algorithm>
#include <filesystem>
#include <direct.h>
#include <limits.h>
#include "MemManagement.h"
#include "ConsolePrinter.h"